import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Main centralized state store for seamless bidirectional sync
  cooperativeState: defineTable({
    key: v.string(), // "main"
    users: v.any(),
    membres: v.any(),
    config: v.any(),
    interventions: v.any(),
    elevages: v.any(),
    parcelles: v.any(),
    terrains: v.any(),
    collectes: v.any(),
    campagnes: v.any(),
    activeCampagneCode: v.string(),
    updatedAt: v.number(),
    updatedBy: v.optional(v.string()),
    syncVersion: v.optional(v.number()),
  }).index("by_key", ["key"]),

  // Granular tables for direct relational querying & individual Convex Table views
  users: defineTable({
    id: v.string(),
    login: v.string(),
    password: v.optional(v.string()),
    nom: v.string(),
    prenom: v.string(),
    email: v.optional(v.string()),
    telephone: v.optional(v.string()),
    role: v.string(),
    fonction: v.optional(v.string()),
    dateAdhesion: v.optional(v.string()),
    statut: v.optional(v.string()),
    dernierAcces: v.optional(v.string()),
    permissions: v.optional(v.any()),
  }).index("by_login", ["login"]).index("by_userId", ["id"]),

  membres: defineTable({
    id: v.string(),
    codeMembre: v.string(),
    nom: v.string(),
    prenom: v.string(),
    genre: v.optional(v.string()),
    telephone: v.optional(v.string()),
    email: v.optional(v.string()),
    commune: v.optional(v.string()),
    ville: v.optional(v.string()),
    pays: v.optional(v.string()),
    statut: v.optional(v.string()),
    partSociales: v.optional(v.number()),
    dateAdhesion: v.optional(v.string()),
    activitePrincipale: v.optional(v.string()),
    domaineActivite: v.optional(v.string()),
    specialite: v.optional(v.string()),
    sections: v.optional(v.array(v.string())),
    detailsSpecifiques: v.optional(v.any()),
  }).index("by_code", ["codeMembre"]).index("by_memberId", ["id"]),

  collectes: defineTable({
    id: v.string(),
    codeCollecte: v.string(),
    date: v.string(),
    campagneCode: v.string(),
    membreId: v.string(),
    produit: v.string(),
    variete: v.optional(v.string()),
    quantite: v.number(),
    unite: v.string(),
    prixUnitaire: v.number(),
    montantTotal: v.number(),
    statutPaiement: v.optional(v.string()),
    lieuStockage: v.optional(v.string()),
    qualite: v.optional(v.string()),
    tauxHumidite: v.optional(v.number()),
    numeroRecu: v.optional(v.string()),
    agentCollecteur: v.optional(v.string()),
    lotTracabilite: v.optional(v.string()),
  }).index("by_campagne", ["campagneCode"]).index("by_membre", ["membreId"]),

  parcelles: defineTable({
    id: v.string(),
    code: v.string(),
    nom: v.string(),
    terrainId: v.string(),
    superficieHa: v.number(),
    typeActivite: v.string(),
    typeSol: v.optional(v.string()),
    irrigation: v.optional(v.boolean()),
    statut: v.optional(v.string()),
    zone: v.optional(v.string()),
    responsable: v.optional(v.string()),
    coordonnees: v.optional(v.any()),
    culturesCohabitantes: v.optional(v.any()),
    elevageLotCode: v.optional(v.string()),
    elevageEspeceNom: v.optional(v.string()),
    superficieElevageHa: v.optional(v.number()),
  }).index("by_code", ["code"]).index("by_terrain", ["terrainId"]),

  terrains: defineTable({
    id: v.string(),
    code: v.string(),
    nom: v.string(),
    proprietaireId: v.string(),
    proprietaireNom: v.string(),
    commune: v.string(),
    superficieHa: v.number(),
    statutFoncier: v.optional(v.string()),
    titreFoncier: v.optional(v.string()),
    dateAcquisition: v.optional(v.string()),
    statutJuridique: v.optional(v.string()),
    coordonnees: v.optional(v.any()),
  }).index("by_code", ["code"]),

  campagnes: defineTable({
    id: v.string(),
    code: v.string(),
    intitule: v.string(),
    type: v.string(),
    dateDebut: v.string(),
    dateFin: v.string(),
    statut: v.string(),
    description: v.optional(v.string()),
    budgetPrevisionnelFCFA: v.optional(v.number()),
    objectifs: v.optional(v.any()),
    parcellesIds: v.optional(v.array(v.string())),
    membresIds: v.optional(v.array(v.string())),
  }).index("by_code", ["code"]),

  elevages: defineTable({
    id: v.string(),
    codeLot: v.string(),
    nomLot: v.string(),
    parcelleId: v.string(),
    especeNom: v.string(),
    raceNom: v.string(),
    effectifActuel: v.number(),
    effectifInitial: v.number(),
    statut: v.string(),
    dateMiseEnPlace: v.string(),
    dateSortiePrevue: v.optional(v.string()),
  }).index("by_code", ["codeLot"]),

  auditLogs: defineTable({
    timestamp: v.number(),
    action: v.string(),
    entity: v.string(),
    userId: v.optional(v.string()),
    details: v.any(),
  }).index("by_timestamp", ["timestamp"]),
});
